<%@ Page Title="" Language="C#" MasterPageFile="~/Template.Master" AutoEventWireup="true" CodeBehind="EvidencijaMain.aspx.cs" Inherits="AntunIT.EvidencijaMain" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <title>Evidencija</title>
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h1>Evidencija tinte po pisačima</h1>
    <asp:AccessDataSource ID="AccessDataSourceTinta" runat="server" DataFile="~/App_Data/Database.mdb" SelectCommand="SELECT pisaci.ID, pisaci.naziv AS Pisač, pisaci.Model, pisaci.vrsta AS VrstaPisača, tinta.model AS VrstaTinte, evidencijaTinte.Dodano FROM pisaci INNER JOIN (tinta INNER JOIN evidencijaTinte ON tinta.ID = evidencijaTinte.idTinte) ON pisaci.ID = evidencijaTinte.idPrinter"></asp:AccessDataSource>
    <asp:GridView ID="GridViewTinta" CssClass="sirokaTablica" DataSourceID="AccessDataSourceTinta" runat="server" AllowPaging="True" PageSize="20" DataKeyNames="ID" AutoGenerateDeleteButton="false" AutoGenerateEditButton="false" AllowSorting="true"></asp:GridView>
    <br /> <br />

    <h1 class="">Evidencija papira po pisačima</h1>
    <asp:AccessDataSource ID="AccessDataSourcePapir" runat="server" DataFile="~/App_Data/Database.mdb" SelectCommand="SELECT pisaci.ID, pisaci.naziv AS Pisač, pisaci.Model, pisaci.vrsta AS VrstaPisača, papir.tip AS VrstaPapira, papir.Format, papir.Komada, evidencijaPapira.Dodano FROM pisaci INNER JOIN (papir INNER JOIN evidencijaPapira ON papir.ID = evidencijaPapira.idPapir) ON pisaci.ID = evidencijaPapira.idPrinter"></asp:AccessDataSource>
    <asp:GridView ID="GridViewPapir" CssClass="sirokaTablica" DataSourceID="AccessDataSourcePapir" runat="server" AllowPaging="True" PageSize="20" DataKeyNames="ID" AutoGenerateDeleteButton="false" AutoGenerateEditButton="false" AllowSorting="true"></asp:GridView>
    

</asp:Content>
