<%@ Page Title="" Language="C#" MasterPageFile="~/Template.Master" AutoEventWireup="true" CodeBehind="PapiraPoPrinteru.aspx.cs" Inherits="AntunIT.PapiraPoPrinteru" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <title>Evidencija papira</title>
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h1 class="">Evidencija papira po pisačima</h1>
    <asp:AccessDataSource ID="AccessDataSourceKorisnici" runat="server" DataFile="~/App_Data/Database.mdb" SelectCommand="SELECT pisaci.ID, pisaci.naziv AS Pisač, pisaci.Model, pisaci.vrsta AS VrstaPisača, papir.tip AS VrstaPapira, papir.Format, papir.Komada, evidencijaPapira.Dodano FROM pisaci INNER JOIN (papir INNER JOIN evidencijaPapira ON papir.ID = evidencijaPapira.idPapir) ON pisaci.ID = evidencijaPapira.idPrinter"></asp:AccessDataSource>
    <asp:GridView ID="GridViewKorisnici" CssClass="sirokaTablica" DataSourceID="AccessDataSourceKorisnici" OnSorting="makniSearch" runat="server" AllowPaging="True" PageSize="20" DataKeyNames="ID" AutoGenerateDeleteButton="false" AutoGenerateEditButton="false" AllowSorting="true"></asp:GridView>
    <br />
    <div id="content" runat="server">
        <asp:Panel runat="server" DefaultButton="TraziBttn">
            <asp:TextBox ID="TraziTb" runat="server" placeholder="Pisač"></asp:TextBox>
            &nbsp;<asp:Button ID="TraziBttn" runat="server" OnClick="Trazi" Text="Traži" />
            &nbsp;<asp:Button ID="PonistiBttn" runat="server" OnClick="Trazi" Text="Poništi" />
        </asp:Panel>
    </div>
    <asp:Button ID="PonistiFilterBttn" runat="server" OnClick="Trazi" Text="Poništi" Visible="false"/>
</asp:Content>
