<%@ Page Title="" Language="C#" MasterPageFile="~/Template.Master" AutoEventWireup="true" CodeBehind="Printers.aspx.cs" Inherits="AntunIT.Printers" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <title>Popis pisača</title>
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h1>Popis pisača</h1>

    <asp:AccessDataSource ID="AccessDataSourcePrinteri" runat="server" DataFile="~/App_Data/Database.mdb" SelectCommand="SELECT ID, Naziv, Model, Vrsta, Lokacija FROM pisaci"></asp:AccessDataSource>
    <asp:GridView ID="GridViewKorisnici" CssClass="tablica" DataSourceID="AccessDataSourcePrinteri" runat="server" AllowPaging="True" PageSize="20" DataKeyNames="ID" AutoGenerateDeleteButton="false" AutoGenerateEditButton="false" AllowSorting="true" OnSorting="makniSearch" OnRowDeleting="printWarning">
        
    </asp:GridView>
  
    <br />
    <div id="content" runat="server">
        <asp:Panel runat="server" DefaultButton="TraziBttn">
            <asp:TextBox ID="TraziTb" runat="server" placeholder="Pisač"></asp:TextBox>
            &nbsp;<asp:Button ID="TraziBttn" runat="server" OnClick="Trazi" Text="Traži" />
            &nbsp;<asp:Button ID="PonistiBttn" runat="server" OnClick="Trazi" Text="Poništi" />
        </asp:Panel>
    </div>
    <asp:Button ID="PonistiFilterBttn" runat="server" OnClick="Trazi" Text="Poništi" Visible="false"/>
</asp:Content>
