<%@ Page Title="" Language="C#" MasterPageFile="~/Template.Master" AutoEventWireup="true" CodeBehind="TintePoPrinteru.aspx.cs" Inherits="AntunIT.TintePoPrinteru" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
        <title>Evidencija tinte</title>
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h1 class="">Evidencija tinte po pisačima</h1>
    <asp:AccessDataSource ID="AccessDataSourceKorisnici" runat="server" DataFile="~/App_Data/Database.mdb" SelectCommand="SELECT pisaci.ID, pisaci.naziv AS Pisač, pisaci.Model, pisaci.vrsta AS VrstaPisača, tinta.model AS VrstaTinte, evidencijaTinte.Dodano FROM pisaci INNER JOIN (tinta INNER JOIN evidencijaTinte ON tinta.ID = evidencijaTinte.idTinte) ON pisaci.ID = evidencijaTinte.idPrinter"></asp:AccessDataSource>
    <asp:GridView ID="GridViewKorisnici" CssClass="sirokaTablica" DataSourceID="AccessDataSourceKorisnici" OnSorting="makniSearch" runat="server" AllowPaging="True" PageSize="20" DataKeyNames="ID" AutoGenerateDeleteButton="false" AutoGenerateEditButton="false" AllowSorting="true" OnRowDataBound="setHeader"></asp:GridView>
    <br />
    <div id="content" runat="server">
        <asp:Panel runat="server" DefaultButton="TraziBttn">
            <asp:TextBox ID="TraziTb" runat="server" placeholder="Pisač"></asp:TextBox>
            &nbsp;<asp:Button ID="TraziBttn" runat="server" OnClick="Trazi" Text="Traži" />
            &nbsp;<asp:Button ID="PonistiBttn" runat="server" OnClick="Trazi" Text="Poništi" />
        </asp:Panel>
    </div>
    <asp:Button ID="PonistiFilterBttn" runat="server" OnClick="Trazi" Text="Poništi" Visible="false"/>
</asp:Content>
