<%@ Page Title="" Language="C#" MasterPageFile="~/Template.Master" AutoEventWireup="true" CodeBehind="UserEdit.aspx.cs" Inherits="AntunIT.WebForm1" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <title>Uredi korisnika</title>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h1 class="">Uredi korisnika</h1>
    <asp:AccessDataSource ID="AccessDataSourceKorisnici" runat="server" DataFile="~/App_Data/Database.mdb" SelectCommand="SELECT id, ime, prezime, email FROM Korisnici" UpdateCommand="UPDATE korisnici SET Ime=?, Prezime=?, Email=? WHERE Id=?">
        <UpdateParameters>
                <asp:ControlParameter ControlID="GridViewKorisnici" Name="Id" PropertyName="SelectedValue" />
                <asp:ControlParameter ControlID="GridViewKorisnici" Name="ime" PropertyName="SelectedValue" />
                <asp:ControlParameter ControlID="GridViewKorisnici" Name="prezime" PropertyName="SelectedValue" />
                <asp:ControlParameter ControlID="GridViewKorisnici" Name="email" PropertyName="SelectedValue" />
        </UpdateParameters>
    </asp:AccessDataSource>
    <asp:GridView ID="GridViewKorisnici" CssClass="tablica" DataSourceID="AccessDataSourceKorisnici" runat="server" AllowPaging="True" PageSize="20" DataKeyNames="ID" AutoGenerateDeleteButton="false" AutoGenerateEditButton="true" AllowSorting="true"></asp:GridView>

</asp:Content>
